In [27]:
import torch

In [28]:
def eval(tensor):
    print("="*50)
    print("Shape:",tensor.shape)
    print("Dimension:",tensor.dim())
    print("Tensor:\n",tensor)
    print("="*50)

In [29]:
tensor  = torch.tensor(
    [1,2,3], 
)
eval(tensor=tensor)

Shape: torch.Size([3])
Dimension: 1
Tensor:
 tensor([1, 2, 3])


In [30]:
tensor = torch.tensor([
    [
        [1,2,3],
        [4,5,8]
    ],
    [
        [1,25,3],
        [45,5,85]
    ],
    [
        [11,2,38.0],
        [43,5,81],
    ]
]
)

eval(tensor=tensor)

Shape: torch.Size([3, 2, 3])
Dimension: 3
Tensor:
 tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  8.]],

        [[ 1., 25.,  3.],
         [45.,  5., 85.]],

        [[11.,  2., 38.],
         [43.,  5., 81.]]])


In [31]:
tensor = torch.rand(size=(1200,1200,3),dtype=float)
eval(tensor=tensor)

Shape: torch.Size([1200, 1200, 3])
Dimension: 3
Tensor:
 tensor([[[0.6076, 0.7384, 0.2524],
         [0.8940, 0.4115, 0.4234],
         [0.4943, 0.3048, 0.0362],
         ...,
         [0.4155, 0.6874, 0.0642],
         [0.2284, 0.3675, 0.3779],
         [0.5517, 0.4743, 0.7960]],

        [[0.5599, 0.0220, 0.7476],
         [0.0204, 0.6972, 0.8585],
         [0.9571, 0.4274, 0.8354],
         ...,
         [0.6941, 0.8689, 0.7903],
         [0.7150, 0.4044, 0.5465],
         [0.7289, 0.5337, 0.1574]],

        [[0.3513, 0.6864, 0.4863],
         [0.8013, 0.6781, 0.8346],
         [0.8937, 0.8126, 0.3042],
         ...,
         [0.8851, 0.3514, 0.0303],
         [0.3624, 0.4437, 0.7281],
         [0.2161, 0.8953, 0.7662]],

        ...,

        [[0.5348, 0.4582, 0.9456],
         [0.3218, 0.4276, 0.4273],
         [0.9154, 0.0043, 0.9348],
         ...,
         [0.5662, 0.6500, 0.4614],
         [0.7237, 0.2526, 0.1188],
         [0.5146, 0.9621, 0.4059]],

        [[0.8676, 0.5547,