In [14]:
import torch

In [15]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [16]:

def eval(tensor):
    print("="*50)
    print("Shape:",tensor.shape)
    print("Dimension:",tensor.dim())
    print("Tensor:\n",tensor)
    print("="*50)

In [17]:
tensor  = torch.tensor(
    [1,2,3], 
)
eval(tensor=tensor)

Shape: torch.Size([3])
Dimension: 1
Tensor:
 tensor([1, 2, 3])


In [18]:
tensor = torch.tensor([
    [
        [1,2,3],
        [4,5,8]
    ],
    [
        [1,25,3],
        [45,5,85]
    ],
    [
        [11,2,38.0],
        [43,5,81],
    ]
]
)

eval(tensor=tensor)

Shape: torch.Size([3, 2, 3])
Dimension: 3
Tensor:
 tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  8.]],

        [[ 1., 25.,  3.],
         [45.,  5., 85.]],

        [[11.,  2., 38.],
         [43.,  5., 81.]]])


In [19]:
tensor = torch.rand(size=(1200,1200,3),dtype=float)
eval(tensor=tensor)

Shape: torch.Size([1200, 1200, 3])
Dimension: 3
Tensor:
 tensor([[[0.4444, 0.3246, 0.0272],
         [0.5843, 0.9595, 0.1701],
         [0.8778, 0.7380, 0.9555],
         ...,
         [0.4037, 0.1418, 0.6834],
         [0.7695, 0.4095, 0.8678],
         [0.2621, 0.3177, 0.1519]],

        [[0.3527, 0.5306, 0.2961],
         [0.5781, 0.1930, 0.4507],
         [0.8753, 0.1262, 0.5863],
         ...,
         [0.4638, 0.9347, 0.2332],
         [0.4380, 0.6505, 0.4746],
         [0.3881, 0.3645, 0.4217]],

        [[0.2655, 0.0378, 0.0025],
         [0.6384, 0.2640, 0.5678],
         [0.2265, 0.6036, 0.5155],
         ...,
         [0.8254, 0.4338, 0.8928],
         [0.1741, 0.8706, 0.1795],
         [0.5826, 0.3344, 0.4566]],

        ...,

        [[0.3823, 0.2887, 0.5628],
         [0.7779, 0.2599, 0.2915],
         [0.5716, 0.6771, 0.4303],
         ...,
         [0.9055, 0.5202, 0.0754],
         [0.8274, 0.9065, 0.4172],
         [0.4370, 0.4353, 0.8264]],

        [[0.0586, 0.3691,

In [20]:
tensor = torch.arange(202,1009120,46863,dtype=torch.float64)
tensor

tensor([2.0200e+02, 4.7065e+04, 9.3928e+04, 1.4079e+05, 1.8765e+05, 2.3452e+05,
        2.8138e+05, 3.2824e+05, 3.7511e+05, 4.2197e+05, 4.6883e+05, 5.1570e+05,
        5.6256e+05, 6.0942e+05, 6.5628e+05, 7.0315e+05, 7.5001e+05, 7.9687e+05,
        8.4374e+05, 8.9060e+05, 9.3746e+05, 9.8432e+05], dtype=torch.float64)

In [21]:
tensor.dtype

torch.float64

In [22]:
tensor = torch.ones_like(tensor)
tensor

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.], dtype=torch.float64)

In [23]:
tensor.dtype

torch.float64

In [24]:
tensor.device

device(type='cpu')

In [25]:
tensor = torch.randn(
    size=(10,2),
    device="cuda"
)

tensor.device

device(type='cuda', index=0)

In [26]:
tensor = tensor.to(device='cpu')
tensor.device

device(type='cpu')