In [40]:
import torch 

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [41]:
tensor_1 = torch.randn(
    size=(3,3),
    device=device,
    requires_grad=True
)

tensor_2 = torch.rand_like(
    input=tensor_1
)

print(f"Tensor 1 : {tensor_1} \nTensor 2 : {tensor_2}")

Tensor 1 : tensor([[-0.9043,  1.3009,  0.0937],
        [ 1.6190,  0.4150,  0.9812],
        [-0.9637,  0.5266, -0.1306]], device='cuda:0', requires_grad=True) 
Tensor 2 : tensor([[0.2255, 0.3999, 0.5923],
        [0.6138, 0.7069, 0.4872],
        [0.6659, 0.4793, 0.0334]], device='cuda:0')


In [42]:
%%time
torch.matmul(tensor_1,tensor_2)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[ 0.6568,  0.6029,  0.1013],
        [ 1.2732,  1.4111,  1.1939],
        [ 0.0189, -0.0758, -0.3186]], device='cuda:0', grad_fn=<MmBackward0>)

In [43]:
%%time
tensor_1*tensor_2

CPU times: total: 0 ns
Wall time: 509 μs


tensor([[-0.2040,  0.5203,  0.0555],
        [ 0.9937,  0.2934,  0.4780],
        [-0.6417,  0.2524, -0.0044]], device='cuda:0', grad_fn=<MulBackward0>)

In [44]:
tensor_1 + tensor_2

tensor([[-0.6787,  1.7008,  0.6860],
        [ 2.2328,  1.1219,  1.4684],
        [-0.2979,  1.0059, -0.0972]], device='cuda:0', grad_fn=<AddBackward0>)

In [45]:
y = tensor_1**2
y

tensor([[0.8177, 1.6922, 0.0088],
        [2.6211, 0.1722, 0.9628],
        [0.9288, 0.2773, 0.0171]], device='cuda:0', grad_fn=<PowBackward0>)